sudo: required
services:
  - docker
language: node_js
node_js:
  - "6"
cache:
  yarn: true
script:
  - yarn run lint
after_success:
  - echo $TRAVIS_BRANCH $TRAVIS_TAG $DOCKER_HUB_EMAIL $DOCKER_HUB_PASS