sudo: required
services:
  - docker
language: node_js
node_js:
  - "6"
cache:
  yarn: true
before_script:
  - yarn run lint
script:
  - if [ "$TRAVIS_TAG" = "" ]; then exit 0; fi
  - export TAG=$TRAVIS_TAG
  - docker-compose build
after_success:
  - if [ "$TRAVIS_TAG" = "" ]; then exit 0; fi
  - docker login -u="$DOCKER_HUB_USER" -p="$DOCKER_HUB_PASS";
  - docker push vanhtuan/react-api-boilerplate;