version: "2.1"

services:
  client:
    build:
      context: .
      args:
        port: ${CLIENT_PORT:-3000}
    image: vanhtuan/redux-api-boilerplate:${TAG:-latest}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./src:/usr/app/src:rw
    ports:
      - ${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}