version: "2.1"

services:
  client:
    build:
      context: .
    image: vanhtuan/redux-api-boilerplate:${TAG:-latest}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
    volumes:
      - ./src:/usr/app/src:rw
    ports:
      - ${PORT:-3000}:${PORT:-3000}